"""Tests that the docs tell the user what the code demands of them.

The per-stage reference lives in docs/stage*.md, so these assert against the
whole doc set rather than the README alone. What must not happen is that a
requirement goes undocumented *anywhere* -- which file carries it is a layout
choice, and moving text between them should not trip a test.
"""

import ast
import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
README = (ROOT / "README.md").read_text()

DOC_FILES = [ROOT / "README.md", *sorted((ROOT / "docs").glob("*.md"))]
DOCS = "\n".join(f.read_text() for f in DOC_FILES)

# Datasets requiring a manual download, with the path speechify_run.py joins
# onto --data-root (or, for persuader, passes via --input_path).
MANUAL_DATASETS = {
    "MultiWOZ": "multiwoz/data/MultiWOZ_2.2/",
    "CraigslistBargain": "CraigslistBargain/train.json",
    "SocraticLM": "SocraticLM/data/SocraTeach_multi.json",
    "DailyPersuasion": None,
}


def test_docs_name_every_manually_downloaded_dataset():
    missing = [d for d in MANUAL_DATASETS if d not in DOCS]
    assert not missing, f"docs do not name these Stage 1 sources: {missing}"


def test_docs_give_the_expected_on_disk_paths():
    missing = [p for p in MANUAL_DATASETS.values() if p and p not in DOCS]
    assert not missing, f"docs omit expected paths: {missing}"


def test_docs_flag_persuader_needing_input_path():
    assert (
        "--input_path" in DOCS
    ), "persuader raises without --input_path (speechify_run.py:123-129); the docs must say so"


# Each stage's reference doc, which the README's pipeline table must link to.
STAGE_DOCS = [
    "docs/stage1-speechify.md",
    "docs/stage2-slots.md",
    "docs/stage3-prediction.md",
    "docs/stage4-generation.md",
    "docs/stage5-tts.md",
]


@pytest.mark.parametrize("rel_path", STAGE_DOCS)
def test_readme_links_every_stage_doc(rel_path):
    """A stage doc the README does not link to is unreachable from the entry
    point, which is the whole reason the detail was moved out of the README.
    """
    assert (ROOT / rel_path).is_file(), f"{rel_path} is missing"
    assert rel_path.removeprefix("docs/") in README, f"README does not link {rel_path}"


INPUT_ROOT_ENTRY_POINTS = [
    "src/train_turntaking_hf.py",
    "src/inference_turntaking_hf.py",
    "src/inference_turntaking_llm.py",
    # Stage 4 had the same defect, plus a default naming a Hub repo path that
    # pointed at the annotations half rather than the dialogues Stage 4 reads:
    # every dataset warned, was skipped, and the run exited 0.
    "src/synthesis/run.py",
    "src/synthesis/run_add_bc.py",
]


@pytest.mark.parametrize("rel_path", INPUT_ROOT_ENTRY_POINTS)
def test_input_root_is_required_not_silently_defaulted(rel_path):
    """A missing path must fail loudly, not yield 'Number of human annotations: 0'."""
    src = (ROOT / rel_path).read_text()
    tree = ast.parse(src)
    found = False
    for node in ast.walk(tree):
        if not (isinstance(node, ast.Call) and getattr(node.func, "attr", "") == "add_argument"):
            continue
        if not node.args or getattr(node.args[0], "value", None) != "--input_root":
            continue
        found = True
        kw = {k.arg: k.value for k in node.keywords}
        assert "default" not in kw, f"--input_root in {rel_path} must not have a default path"
        assert (
            getattr(kw.get("required"), "value", False) is True
        ), f"--input_root in {rel_path} must be required=True"
    assert found, f"--input_root argument not found in {rel_path}"


@pytest.mark.parametrize("doc", DOC_FILES, ids=lambda p: p.name)
def test_documented_input_root_values_are_parent_directories(doc):
    """--input_root is joined with each scenario folder underneath it, so a
    documented value that is itself a text_dialogue_* path resolves to a
    nonexistent, double-nested directory and silently yields zero annotations.

    Every doc that shows a command counts, not just the README -- this has
    already shipped wrong in docs/ once.
    """
    values = re.findall(r"--input_root\s+(\S+?)\s*\\?\s*$", doc.read_text(), flags=re.MULTILINE)
    bad = [v for v in values if "text_dialogue_" in v]
    assert not bad, f"{doc.name}: --input_root must be the parent of text_dialogue_*, got {bad}"


def test_readme_documents_at_least_one_input_root_command():
    assert "--input_root" in README, "no documented --input_root values found in README"


def test_stage3_documents_the_token_classifier_not_post_hoc_calibration():
    """The released corpus was generated by the fine-tuned Qwen3 classifier
    (tt_mode="hf_classification"); post-hoc Platt/temperature scaling is the
    approach the paper argues against in Section 3.2 and is not in this repo.
    """
    stage3 = (ROOT / "docs/stage3-prediction.md").read_text()
    assert "src.train_turntaking_hf" in stage3
    assert "--input_root" in stage3.split("src.train_turntaking_hf", 1)[1]
    for banned in ("platt", "temperature scaling", "src.calibration"):
        assert banned not in DOCS.lower(), f"docs still document {banned!r}"


# Documented commands, and the argparse-owning source file each one runs.
# A package entry point (python -m src.synthesis.run) parses its arguments in
# the module the -m path names, which is not always a module named after the
# package.
DOCUMENTED_ENTRY_POINTS = {
    "src.speechify_run": "src/speechify_run.py",
    "src.train_turntaking_hf": "src/train_turntaking_hf.py",
    "src.inference_turntaking_hf": "src/inference_turntaking_hf.py",
    "src.inference_turntaking_llm": "src/inference_turntaking_llm.py",
    "src.synthesis.run": "src/synthesis/run.py",
    "src.synthesis.run_add_bc": "src/synthesis/run_add_bc.py",
}


def _required_options(rel_path):
    """Every option string argparse marks required=True in a source file.

    Subparser arguments are skipped: they are required only for the subcommand
    that defines them, which this flat scan cannot attribute.
    """
    tree = ast.parse((ROOT / rel_path).read_text())
    subparser_vars = set()
    for node in ast.walk(tree):
        if (
            isinstance(node, ast.Assign)
            and isinstance(node.value, ast.Call)
            and getattr(node.value.func, "attr", "") == "add_parser"
        ):
            for target in node.targets:
                if isinstance(target, ast.Name):
                    subparser_vars.add(target.id)

    required = []
    for node in ast.walk(tree):
        if not (isinstance(node, ast.Call) and getattr(node.func, "attr", "") == "add_argument"):
            continue
        if getattr(node.func.value, "id", None) in subparser_vars:
            continue
        kw = {k.arg: k.value for k in node.keywords}
        if getattr(kw.get("required"), "value", False) is not True:
            continue
        flags = [a.value for a in node.args if isinstance(getattr(a, "value", None), str)]
        opts = [f for f in flags if f.startswith("-")]
        if opts:
            required.append(opts)
    return required


def _documented_commands():
    """(doc name, module, full command text) for every `-m src.<module>` in a code block."""
    found = []
    for doc in DOC_FILES:
        for block in re.findall(r"```bash\n(.*?)```", doc.read_text(), flags=re.DOTALL):
            # Join backslash continuations so a multi-line command is one string.
            for command in re.sub(r"\\\n\s*", " ", block).splitlines():
                match = re.search(r"-m\s+(src\.[\w.]+)", command)
                if match:
                    found.append((doc.name, match.group(1), command))
    return found


def test_every_documented_module_is_a_known_entry_point():
    unknown = {m for _, m, _ in _documented_commands() if m not in DOCUMENTED_ENTRY_POINTS}
    assert (
        not unknown
    ), f"documented modules missing from DOCUMENTED_ENTRY_POINTS: {sorted(unknown)}"


def test_documented_commands_pass_every_required_argument():
    """A documented command that omits a required= argument dies on argparse.

    README's Stage 3 example ran `-m src.inference_turntaking_llm --split test
    --scenarios all` and exited 2 with "the following arguments are required:
    --input_root" before doing any work.
    """
    broken = []
    for doc_name, module, command in _documented_commands():
        for aliases in _required_options(DOCUMENTED_ENTRY_POINTS[module]):
            if not any(
                re.search(rf"(?<![\w-]){re.escape(a)}(?=[\s=]|$)", command) for a in aliases
            ):
                broken.append(f"{doc_name}: `{module}` omits required {'/'.join(aliases)}")
    assert not broken, "documented commands fail argparse:\n  " + "\n  ".join(broken)


def test_project_is_pip_installable():
    assert (ROOT / "pyproject.toml").is_file(), "no packaging metadata at the repo root"


def test_pyproject_declares_the_required_core_metadata():
    import tomllib

    data = tomllib.loads((ROOT / "pyproject.toml").read_text())
    project = data["project"]
    for field in ("name", "version", "description", "requires-python", "license"):
        assert field in project, f"pyproject [project] is missing {field}"
    assert project["requires-python"].startswith(">=3.10"), project["requires-python"]


def test_reuse_toml_covers_the_major_trees():
    import tomllib

    data = tomllib.loads((ROOT / "REUSE.toml").read_text())
    paths = {
        entry["path"] if isinstance(entry["path"], str) else entry["path"][0]
        for entry in data["annotations"]
    }
    for required in ("**", "vilex/tts/chatterbox/**", "tts_render/librispeech_samples/**"):
        assert any(p == required for p in paths), f"REUSE.toml does not annotate {required}"

    by_path = {
        entry["path"] if isinstance(entry["path"], str) else entry["path"][0]: entry
        for entry in data["annotations"]
    }
    expected_licenses = {
        "**": "Apache-2.0",
        "vilex/tts/chatterbox/**": "MIT",
        "tts_render/librispeech_samples/**": "CC-BY-4.0",
        "tts_render/prompt_wavs/**": "CC-BY-4.0",
    }
    for path, expected in expected_licenses.items():
        assert path in by_path, f"REUSE.toml does not annotate {path}"
        found = by_path[path]["SPDX-License-Identifier"]
        assert found == expected, f"REUSE.toml licenses {path} as {found!r}, expected {expected!r}"
